# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 10
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
    providers:
        our_db_provider:
            entity:
                class: AppBundle\Entity\User
                property: user_email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                check_path: login
                login_path: login
                provider: our_db_provider
                csrf_token_generator: security.csrf.token_manager
                default_target_path: home
                always_use_default_target_path: true
            logout:
                path: logout
                target: login
